# This file was generated by GoReleaser. DO NOT EDIT.
class Acyl < Formula
  desc "Testing Environments On Demand"
  homepage ""
  version "0.7.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dollarshaveclub/acyl/releases/download/v0.7.6/acyl_0.7.6_MacOS_x86_64.tar.gz"
    sha256 "d0de9e20340d1bd51e8cc3549b12307730b6dada8a26bb1f2a26950224fa16b5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dollarshaveclub/acyl/releases/download/v0.7.6/acyl_0.7.6_Linux_x86_64.tar.gz"
      sha256 "28b3bcf4ad68054895afe69d39d4e126fc32057cc210568b5c9b4f819b74aa95"
    end
  end

  def install
    bin.install "acyl"
    pkgshare.mkpath
    pkgshare.install "data/words.json.gz"
    (pkgshare/"ui").mkpath
    (pkgshare/"ui/views").mkpath
    (pkgshare/"ui/views").install Dir["ui/views/*"]
    (pkgshare/"ui/assets").mkpath
    (pkgshare/"ui/assets").install Dir["ui/assets/*"]
  end
end
