# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acyl < Formula
  desc "Testing Environments On Demand"
  homepage ""
  version "0.9.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dollarshaveclub/acyl/releases/download/v0.9.0/acyl_0.9.0_MacOS_x86_64.tar.gz"
      sha256 "671042a4adda2486151208f408274b7b232aa37a43a99ec2f91387d80e513724"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dollarshaveclub/acyl/releases/download/v0.9.0/acyl_0.9.0_Linux_x86_64.tar.gz"
      sha256 "ce36fde42054f67143a1d5c71ee4533f9f7bbc9bbe614b47dc77bacc85c17075"
    end
  end

  def install
    bin.install "acyl"
    pkgshare.mkpath
    pkgshare.install "data/words.json.gz"
    (pkgshare/"ui").mkpath
    (pkgshare/"ui/views").mkpath
    (pkgshare/"ui/views").install Dir["ui/views/*"]
    (pkgshare/"ui/assets").mkpath
    (pkgshare/"ui/assets").install Dir["ui/assets/*"]
  end
end
