# This file was generated by GoReleaser. DO NOT EDIT.
class Acyl < Formula
  desc "Testing Environments On Demand"
  homepage ""
  url "https://github.com/dollarshaveclub/acyl/releases/download/v0.6.2/acyl_0.6.2_MacOS_x86_64.tar.gz"
  version "0.6.2"
  sha256 "a85272b8b927c9d2d7de1f1111a6ac7c202fd54c486a69454efc17e49e78bc5e"

  def install
    bin.install "acyl"
    pkgshare.mkpath
    pkgshare.install "data/words.json.gz"
  end
end
