# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thermite < Formula
  desc "Removes old Amazon Elastic Container Registry images that are not deployed in a Kubernetes cluster"
  homepage "https://github.com/dollarshaveclub/thermite"
  version "0.0.27"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.27/thermite_0.0.27_darwin_amd64.tar.gz"
      sha256 "f640a4e825fd6f4ae2867f6f9ceefa3a0d6e9ab2d0a5c812b6046e057c47945d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.27/thermite_0.0.27_darwin_arm64.tar.gz"
      sha256 "2e42713a454d6fbd37087bf76892a6cc16ae9999637c24f18021bd558a11c7a6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.27/thermite_0.0.27_linux_amd64.tar.gz"
      sha256 "4a46d622644cfc8de5d960ebcdd646891d64c590b2257668694ca5a4b9c584db"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.27/thermite_0.0.27_linux_arm64.tar.gz"
      sha256 "abe72d7fe2f8b0be405f6e4a6cb53e83e658f4fc39b1892e4294d57fbe98ba5c"
    end
  end

  def install
    bin.install "thermite"
  end
end
