# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thermite < Formula
  desc "Removes old Amazon Elastic Container Registry images that are not deployed in a Kubernetes cluster"
  homepage "https://github.com/dollarshaveclub/thermite"
  version "0.0.17"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.17/thermite_0.0.17_darwin_amd64.tar.gz"
      sha256 "2e9fada99a1123c440d7737cc9d2014eb48839c6d941155dd479dae7143f18d9"
    end
    if Hardware::CPU.arm?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.17/thermite_0.0.17_darwin_arm64.tar.gz"
      sha256 "2f63fa4a47f195a2fa2a4d2a562d5413db9e9cda26fbb32c073451105b0c7df3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.17/thermite_0.0.17_linux_amd64.tar.gz"
      sha256 "3b74360bc15779429a3d9feb5f678c199dd772dc7e35ffd7e15dca9465619fb3"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.17/thermite_0.0.17_linux_arm64.tar.gz"
      sha256 "bac9836c05877088b37ddc584b397300b9a3dc348d273e4118e8a8d1245d104e"
    end
  end

  def install
    bin.install "thermite"
  end
end
