# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thermite < Formula
  desc "Removes old Amazon Elastic Container Registry images that are not deployed in a Kubernetes cluster"
  homepage "https://github.com/dollarshaveclub/thermite"
  version "0.0.31"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.31/thermite_0.0.31_darwin_amd64.tar.gz"
      sha256 "8d4fd407466d6e519d0ba764b89282df2fad752bf170c1b2dbb7ad292fccdf30"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.31/thermite_0.0.31_linux_amd64.tar.gz"
      sha256 "c2b6025c47d6b4bb87427928f116ef96155e5a3efa6c95ce219e95702113b3bd"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dollarshaveclub/thermite/releases/download/v0.0.31/thermite_0.0.31_linux_arm64.tar.gz"
      sha256 "e0acd450d46fa3525440e1899cedf32a8a09f532bc747cd569cbdc48863d4c84"
    end
  end

  def install
    bin.install "thermite"
  end
end
